version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: reactive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
